### ISSUE TITLE
Acquire star database

### ISSUE THREAD

**Issue by jokkehasa** [jokkehasa/brightest-star#1]
Acquire and prepare a database of stars (name, magnitude, celestial coordinates in the current epoch)

**Comment by jokkehasa** [comment]
Planning to use the HYG database (https://github.com/astronexus/HYG-Database), but need to change to CC-BY-SA license for that.

**Comment by jokkehasa** [comment]
Copied HYG database and changed license.

**Comment by amiha017-xamk** [comment]
Maybe we should abandon HYG database and consider using Yale Bright Star Catalog which consists only stars visible to naked eye and is considerable lighter to use.

**Comment by amiha017-xamk** [comment]
HYG-data edited. Sun and dim stars (mag>6) deleted.
